http {
  upstream users {
    server users-service:8081;
  }
  upstream products {
    server products-service:8082;
  }
  upstream payments {
    server payments-service:8083;
  }

  server {
    listen 4500;

    location /users {
      proxy_pass http://users;
    }
    location /products {
      proxy_pass http://products;
    }
    location /payments {
      proxy_pass http://payments;
    }
  }
}
events { }
